version: "3.4"

services:
  api:
    container_name: clean-boilerplate_prod-api-service
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    # image: clean-boilerplate
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn start
    restart: always

networks:
  default:
    name: clean-boilerplate-api-default